services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true

  backend:
    image: rag-backend:latest # Image built locally
    container_name: backend
    ports:
      - "8000:8000"
    depends_on:
      - ollama
    environment:
      - OLLAMA_HOST=ollama
      - OLLAMA_PORT=11434
      - PG_VECTOR_DATABASE_URL=postgresql://demo_user:demo_password@vectordb:5432/rag_db
    restart: unless-stopped

  ollama:
    image: rag-ollama:latest  # Image built locally
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

  vectordb:
    image: pgvector/pgvector:pg16
    container_name: pgvector_db
    environment:
      POSTGRES_DB: rag_db
      POSTGRES_USER: demo_user
      POSTGRES_PASSWORD: demo_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./pgvector/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

volumes:
  ollama_data: 

  postgres_data: